version: '3.7'

services:
  app:
    container_name: vinopinionsapp-devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    network_mode: host
    volumes:
      - ..:/workspace
    user: dev
