name: Release
on:
  push:
    branches: ['master']

permissions:
  contents: read # for checkout

jobs:
  codeql:
    uses: ./.github/workflows/codeql.yml
    permissions:
      actions: read
      security-events: write
      contents: read

  eslint:
    uses: ./.github/workflows/eslint.yml
    permissions:
      security-events: write
      contents: read

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests

    needs:
      - codeql
      - eslint

    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ vars.RELEASE_BOT_ID }}
          private_key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate_token.outputs.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        run: yarn --ignore-scripts --non-interactive --frozen-lockfile

      - name: Create github release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: yarn release
